import type { ServiceCity, ServiceZone } from "../application/useServiceAreas";

/**
 * Référentiel de secours des zones de service.
 *
 * Les villes et les quartiers vivent en base, pour qu'ouvrir une nouvelle ville
 * relève de l'exploitation et non d'une livraison de code. Mais un formulaire
 * dont la liste de villes est vide n'est pas dégradé, il est inutilisable : le
 * client ne peut plus commander du tout.
 *
 * Ce référentiel est donc la copie, figée à la livraison, de ce que la
 * migration installe en base. Il ne sert que lorsque la base ne répond pas ou
 * ne porte pas encore ces tables. Dès qu'elle répond, elle fait autorité.
 *
 * Ce fichier est généré depuis les migrations : ne pas l'éditer à la main, au
 * risque de le voir diverger silencieusement de la base.
 */

export const VILLES_DE_SECOURS: ServiceCity[] = [
  { slug: "abidjan", name: "Abidjan", region: "Lagunes", lat: 5.3364, lng: -4.0267, errandsEnabled: true },
  { slug: "grand-bassam", name: "Grand-Bassam", region: "Sud-Comoé", lat: 5.2118, lng: -3.7387, errandsEnabled: false },
  { slug: "assinie", name: "Assinie", region: "Sud-Comoé", lat: 5.1333, lng: -3.2833, errandsEnabled: false },
  { slug: "yamoussoukro", name: "Yamoussoukro", region: "Lacs", lat: 6.8276, lng: -5.2893, errandsEnabled: false },
  { slug: "bouake", name: "Bouaké", region: "Vallée du Bandama", lat: 7.6939, lng: -5.0303, errandsEnabled: false },
  { slug: "san-pedro", name: "San-Pédro", region: "Bas-Sassandra", lat: 4.7485, lng: -6.6363, errandsEnabled: false },
  { slug: "korhogo", name: "Korhogo", region: "Savanes", lat: 9.4578, lng: -5.6294, errandsEnabled: false },
  { slug: "daloa", name: "Daloa", region: "Haut-Sassandra", lat: 6.8772, lng: -6.4502, errandsEnabled: false },
];

export const QUARTIERS_DE_SECOURS: ServiceZone[] = [
  { citySlug: "abidjan", name: "Cocody Centre", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Riviera 2", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Riviera 3", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Riviera 4", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Riviera Palmeraie", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Riviera Bonoumin", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Angré", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Angré 7e Tranche", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Deux Plateaux", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Deux Plateaux Vallon", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Danga", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Blockhauss", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Mermoz", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Attoban", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Faya", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Abatta", parentName: "Cocody" },
  { citySlug: "abidjan", name: "Plateau Centre", parentName: "Plateau" },
  { citySlug: "abidjan", name: "Plateau Dokui", parentName: "Plateau" },
  { citySlug: "abidjan", name: "Cité Administrative", parentName: "Plateau" },
  { citySlug: "abidjan", name: "Marcory Résidentiel", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Zone 4", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Biétry", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Remblais", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Anoumabo", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Konan Raphaël", parentName: "Marcory" },
  { citySlug: "abidjan", name: "Treichville Centre", parentName: "Treichville" },
  { citySlug: "abidjan", name: "Arras", parentName: "Treichville" },
  { citySlug: "abidjan", name: "Belleville", parentName: "Treichville" },
  { citySlug: "abidjan", name: "Zone 3", parentName: "Treichville" },
  { citySlug: "abidjan", name: "Biafra", parentName: "Treichville" },
  { citySlug: "abidjan", name: "Yopougon Selmer", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Niangon", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Niangon Sud", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Sideci", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Toits Rouges", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Maroc", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Ananeraie", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Banco", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Andokoi", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Gesco", parentName: "Yopougon" },
  { citySlug: "abidjan", name: "Abobo Centre", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Abobo Baoulé", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Anonkoua Kouté", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Sagbé", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Avocatier", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Plaque", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Belleville Abobo", parentName: "Abobo" },
  { citySlug: "abidjan", name: "Adjamé Centre", parentName: "Adjamé" },
  { citySlug: "abidjan", name: "Williamsville", parentName: "Adjamé" },
  { citySlug: "abidjan", name: "Bracodi", parentName: "Adjamé" },
  { citySlug: "abidjan", name: "220 Logements", parentName: "Adjamé" },
  { citySlug: "abidjan", name: "Liberté", parentName: "Adjamé" },
  { citySlug: "abidjan", name: "Koumassi Centre", parentName: "Koumassi" },
  { citySlug: "abidjan", name: "Remblais Koumassi", parentName: "Koumassi" },
  { citySlug: "abidjan", name: "Sicogi", parentName: "Koumassi" },
  { citySlug: "abidjan", name: "Campement", parentName: "Koumassi" },
  { citySlug: "abidjan", name: "Divo", parentName: "Koumassi" },
  { citySlug: "abidjan", name: "Port-Bouët Centre", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Vridi", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Vridi Cité", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Gonzagueville", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Adjouffou", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Anani", parentName: "Port-Bouët" },
  { citySlug: "abidjan", name: "Attécoubé Centre", parentName: "Attécoubé" },
  { citySlug: "abidjan", name: "Locodjro", parentName: "Attécoubé" },
  { citySlug: "abidjan", name: "Agban Village", parentName: "Attécoubé" },
  { citySlug: "abidjan", name: "Santé", parentName: "Attécoubé" },
  { citySlug: "abidjan", name: "Bingerville Centre", parentName: "Bingerville" },
  { citySlug: "abidjan", name: "Adjin", parentName: "Bingerville" },
  { citySlug: "abidjan", name: "Songon Centre", parentName: "Songon" },
  { citySlug: "abidjan", name: "Anyama Centre", parentName: "Anyama" },
  { citySlug: "grand-bassam", name: "Quartier France", parentName: null },
  { citySlug: "grand-bassam", name: "Moossou", parentName: null },
  { citySlug: "grand-bassam", name: "Petit Paris", parentName: null },
  { citySlug: "grand-bassam", name: "Oddos", parentName: null },
  { citySlug: "grand-bassam", name: "Impérial", parentName: null },
  { citySlug: "grand-bassam", name: "Mockeyville", parentName: null },
  { citySlug: "grand-bassam", name: "Azuretti", parentName: null },
  { citySlug: "grand-bassam", name: "Vitré", parentName: null },
  { citySlug: "assinie", name: "Assinie-Mafia", parentName: null },
  { citySlug: "assinie", name: "Assinie France", parentName: null },
  { citySlug: "assinie", name: "Assouindé", parentName: null },
  { citySlug: "assinie", name: "Bracodi Plage", parentName: null },
  { citySlug: "assinie", name: "Ébra", parentName: null },
  { citySlug: "yamoussoukro", name: "Centre-ville", parentName: null },
  { citySlug: "yamoussoukro", name: "Habitat", parentName: null },
  { citySlug: "yamoussoukro", name: "Millionnaire", parentName: null },
  { citySlug: "yamoussoukro", name: "Kokrenou", parentName: null },
  { citySlug: "yamoussoukro", name: "Morofé", parentName: null },
  { citySlug: "yamoussoukro", name: "Dioulakro", parentName: null },
  { citySlug: "yamoussoukro", name: "Assabou", parentName: null },
  { citySlug: "yamoussoukro", name: "Riviera Yamoussoukro", parentName: null },
  { citySlug: "bouake", name: "Commerce", parentName: null },
  { citySlug: "bouake", name: "Air France", parentName: null },
  { citySlug: "bouake", name: "Koko", parentName: null },
  { citySlug: "bouake", name: "Dar Es Salam", parentName: null },
  { citySlug: "bouake", name: "Belleville", parentName: null },
  { citySlug: "bouake", name: "Nimbo", parentName: null },
  { citySlug: "bouake", name: "Ahougnansou", parentName: null },
  { citySlug: "bouake", name: "Kennedy", parentName: null },
  { citySlug: "bouake", name: "Sokoura", parentName: null },
  { citySlug: "bouake", name: "Broukro", parentName: null },
  { citySlug: "san-pedro", name: "Cité", parentName: null },
  { citySlug: "san-pedro", name: "Bardot", parentName: null },
  { citySlug: "san-pedro", name: "Séweké", parentName: null },
  { citySlug: "san-pedro", name: "Balmer", parentName: null },
  { citySlug: "san-pedro", name: "Lac", parentName: null },
  { citySlug: "san-pedro", name: "Zone Portuaire", parentName: null },
  { citySlug: "san-pedro", name: "Poro", parentName: null },
  { citySlug: "korhogo", name: "Centre-ville", parentName: null },
  { citySlug: "korhogo", name: "Soba", parentName: null },
  { citySlug: "korhogo", name: "Petit Paris", parentName: null },
  { citySlug: "korhogo", name: "Koko Korhogo", parentName: null },
  { citySlug: "korhogo", name: "Résidentiel", parentName: null },
  { citySlug: "korhogo", name: "Banaforo", parentName: null },
  { citySlug: "korhogo", name: "Sinistré", parentName: null },
  { citySlug: "daloa", name: "Commerce", parentName: null },
  { citySlug: "daloa", name: "Lobia", parentName: null },
  { citySlug: "daloa", name: "Tazibouo", parentName: null },
  { citySlug: "daloa", name: "Kennedy", parentName: null },
  { citySlug: "daloa", name: "Orly", parentName: null },
  { citySlug: "daloa", name: "Huberson", parentName: null },
  { citySlug: "daloa", name: "Baoulé", parentName: null },
];
