import { execFileSync } from "node:child_process";
const url = execFileSync("git", ["ls-remote", "--get-url", "origin"], { encoding: "utf8" }).trim();
const m = url.match(/github\.com[:/]([^/]+)\/(.+?)(?:\.git)?$/);
const sortie = execFileSync("git", ["credential", "fill"], { input: "protocol=https\nhost=github.com\n\n", encoding: "utf8" });
const cle = sortie.split(/\r?\n/).find((l) => l.startsWith("password=")).slice(9);
const h = { Authorization: `Bearer ${cle}`, Accept: "application/vnd.github+json" };
const jobs = await (await fetch(`https://api.github.com/repos/${m[1]}/${m[2]}/actions/runs/33111468521/jobs`, { headers: h })).json();
const j = jobs.jobs.find(x => x.conclusion === "failure");
const log = await (await fetch(`https://api.github.com/repos/${m[1]}/${m[2]}/actions/jobs/${j.id}/logs`, { headers: h, redirect: "follow" })).text();
const lignes = log.split(/\r?\n/).filter(l => /error|Error|TS\d|failed|✖/.test(l));
console.log(lignes.slice(0, 25).join("\n"));
